name: Run backend tests

on: [push]

jobs:
    Backend-Test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./apps/backend
        
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install bun
              uses: oven-sh/setup-bun@v2              

            - name: Install dependencies
              run: bun install

            - name: Run tests
              run: bun run test

